### PR TITLE
ParseError for DTDs

### PR DESCRIPTION
**Pull request by jannik38**
Hello,

If you parse an xsd file that contains DTDs with the current version, you will get a ParseError. However, if you disable DTD support in XMLInputFactory, it works.

Best regards

### CODE REVIEW

**Review by predic8 — CHANGES_REQUESTED** [review]
Thanks. Please take out the eclipse project files and keep the AbstractParser

**Review by predic8 — CHANGES_REQUESTED** [review]
Take out the eclipse project files

**Comment by saschagrebe** [comment]
@predic8 Is it possible to merge the issue and release a new version? @jannik38 fixed the requested change.

**Comment by predic8** [comment]
Hi @saschagrebe,
PR is merged. We only release when something is really urgent cause this is technology from 20 years ago.

**Pull request merged**
